# Generated by Django 4.0.3 on 2022-04-03 09:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220213_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='متن'),
        ),
    ]
