# Generated by Django 4.0.3 on 2022-04-03 09:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='about',
            field=tinymce.models.HTMLField(),
        ),
    ]
