# Generated by Django 4.0.3 on 2022-04-03 09:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_sitesetting_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='about',
            field=tinymce.models.HTMLField(verbose_name='درباره ی ما'),
        ),
    ]
