# Generated by Django 4.0.3 on 2022-04-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_sitesetting_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'تنظیم', 'verbose_name_plural': 'تنظیم ها'},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about',
            field=models.TextField(verbose_name='درباره ی ما'),
        ),
    ]
